### ISSUE TITLE
ファイルから開いた後に連続変形(自動)が使えない

### ISSUE THREAD

**Issue by shwaka** [UTMS-VR/DeformingKnot#28]
再現方法:
1. ファイルから結び目を読み込む
2. 連続変形(自動)を行う

症状:
- 連続変形(自動)に失敗する
- メニューに戻ることもできない
- 連続変形(手動)は大丈夫

**Comment by 1123sodium** [comment]
`knot_3_1.json`, `knot_6_2.json`(自分の環境では`ochiai_unknot.json`も)でバグが発生する.
